export const SIGNUP_SUCSESS = 'SIGNUP_SUCSESS';
export const SIGNUP_FAILED = 'SIGNUP_FAILED';
export const SIGNIN_SUCCESS = 'SIGNIN_SUCCESS';
export const SIGNIN_FAILED = 'SIGNIN_FAILED';
export const CREATE_BLOGS_SUCCESS = 'CREATE_BLOGS_SUCCESS';
export const CREATE_BLOGS_FAILED = 'FETCH_BLOGS_FAILED';
